apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bad-ingress
  annotations:
    nginx.ingress.kubernetes.io/permanent-redirect: https://example.com
spec:
  rules:
  - host: myapp.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myapp-service
            port:
              number: 80
