apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-secrets-store-csi-driver-loglevel
  annotations:
    policies.kyverno.io/title: Prevent CVE-2023-2878
    policies.kyverno.io/category: Security
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Deployment, DaemonSet
    kyverno.io/kyverno-version: 1.11.0
    kyverno.io/kubernetes-version: 1.27
    policies.kyverno.io/description: >-
      Prevent CVE-2023-2878 which can leak security tokens when using the csidriver secrets store. The policy checks if you are using the store and warns you could be vulnerable.

      Refer to the documentation for more details on Kyverno annotations: https://artifacthub.io/docs/topics/annotations/kyverno/
spec:
  validationFailureAction: Audit
  rules:
  - name: limit-secrets-store-csi-driver-loglevel
    match:
      any:
      - resources:
          kinds:
          - Deployment
          - DaemonSet
    validate:
      message: "secrets-store-csi-driver must use log level 1 or below, CVE-2023-2878."
      pattern:
        spec:
          template:
            spec:
              containers:
                - name: "secrets-store"
                  args: "-v=0 | -v=1"
