apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bad-ingress
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /testpath
        pathType: Exact
        backend:
          service:
            name: test-service
            port:
              number: 80
