apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: secrets-not-from-env-vars-cve-2024-3177
spec:
  steps:
  - name: step-01
    try:
    - apply:
        file: ../secrets-not-from-env-vars-cve-2024-3177.yaml
    - patch:
        resource:
          apiVersion: kyverno.io/v1
          kind: ClusterPolicy
          metadata:
            name: secrets-not-from-env-vars-cve-2024-3177
          spec:
            validationFailureAction: Enforce
    - assert:
        file: chainsaw-step-01-assert-1.yaml
  - name: step-02
    try:
    - apply:
        file: good-pod.yaml
    - apply:
        expect:
        - check:
            ($error != null): true
        file: bad-pod.yaml
