apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: good-rolebinding
  namespace: default
subjects:
- kind: User
  name: john.doe
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io
