apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secrets-store
  template:
    metadata:
      labels:
        app: secrets-store
    spec:
      containers:
      - name: secrets-store
        image: secrets-store-csi-driver:latest
        args: ["-v=2"]
