apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: good-daemonset
  namespace: default
spec:
  selector:
    matchLabels:
      app: secrets-store
  template:
    metadata:
      labels:
        app: secrets-store
    spec:
      containers:
      - name: secrets-store
        image: secrets-store-csi-driver:latest
        args: ["-v=0"]
